### ISSUE TITLE
PC端使用

### ISSUE THREAD

**Issue by Vicent9920** [huanz/surge-hosts#17]
你这个工具应该怎么使用啊？
除了修改hosts文件以外，还要修改ipv6_hosts文件吗？如果需要的话，这个文件在什么地方啊？

**Comment by huanz** [comment]
提供两种hosts，一种就是普通的ipv4的，一种是ipv6，你可以选择其中一种配置 yhz1219 邮箱：yhz1219@gmail.com 签名由 网易邮箱大师 定制 在2018年04月21日 10:19，Vicent9920 写道： 你这个工具应该怎么使用啊？ 除了修改hosts文件以外，还要修改ipv6_hosts文件吗？如果需要的话，这个文件在什么地方啊？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
