### ISSUE TITLE
你好，麻烦请教一下，你这个conf文件如何使用啊？

### ISSUE THREAD

**Issue by xu2006** [huanz/surge-hosts#8]
你好，麻烦请教一下，你这个conf文件如何使用啊？
麻烦直到一下，谢谢！

**Comment by huanz** [comment]
打开surge，然后在配置界面选择：Download Configuration from Url，输入conf链接地址

在2017年04月17日 20:50，xu2006 写道： 你好，麻烦请教一下，你这个conf文件如何使用啊？
麻烦直到一下，谢谢！

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/huanz/surge-hosts","title":"huanz/surge-hosts","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/huanz/surge-hosts"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"你好，麻烦请教一下，你这个conf文件如何使用啊？ (#8)"}],"action":{"name":"View Issue","url":"https://github.com/huanz/surge-hosts/issues/8"}}}
